SET
REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE `member`;
TRUNCATE TABLE `baby`;
TRUNCATE TABLE `token`;
TRUNCATE TABLE `content`;
TRUNCATE TABLE `relation_group`;
TRUNCATE TABLE `like_table`;
TRUNCATE TABLE `comment`;
TRUNCATE TABLE `relation`;
TRUNCATE TABLE `invitation`;
TRUNCATE TABLE `tag`;

SET
REFERENTIAL_INTEGRITY TRUE