SET
REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE `member`;
TRUNCATE TABLE `baby`;
TRUNCATE TABLE `relation`;
TRUNCATE TABLE `content`;
TRUNCATE TABLE `like_table`;
TRUNCATE TABLE `token`;


SET
REFERENTIAL_INTEGRITY TRUE