name : pullrequest ci

on:
  pull_request:
    branches: [ dev, main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: ./back
      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ./back
        env:
          JWT_ACCESS_EXPIRE_LENGTH: ${{ secrets.JWT_ACCESS_EXPIRE_LENGTH }}
          JWT_ACCESS_SECRET_KEY: ${{ secrets.JWT_ACCESS_SECRET_KEY }}
          JWT_REFRESH_EXPIRE_LENGTH: ${{ secrets.JWT_REFRESH_EXPIRE_LENGTH }}
          JWT_REFRESH_SECRET_KEY: ${{ secrets.JWT_REFRESH_SECRET_KEY }}
          JWT_SIGN_EXPIRE_LENGTH: ${{ secrets.JWT_SIGN_EXPIRE_LENGTH }}
          JWT_SIGN_SECRET_KEY: ${{ secrets.JWT_SIGN_SECRET_KEY }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_IMAGES_BUCKET_NAME: ${{ secrets.S3_IMAGES_BUCKET_NAME }}
